---
- name: dnf upgrade
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Install base packages
  ansible.builtin.dnf:
    name: >-
      {{ common_base_packages_rocky
         | reject('equalto','qemu-guest-agent')
         | list if guest_kind == 'lxc'
         else common_base_packages_rocky }}
    state: present

- name: Enable and start qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
    enabled: true
  when: guest_kind == "vm"
