---
- name: Seed Proxmox templates
  hosts: "{{ target_node }}"
  gather_facts: false
  become: false
  roles:
    - role: seed_ubuntu_vm
    - role: seed_rocky_vm
    - role: seed_ubuntu_lxc
    - role: seed_rocky_lxc
